name: Build docker image

on:
  workflow_call:
    inputs:
      cache:
        type: string
      name:
        required: true
        type: string
      context:
        type: string
        default: .
      file:
        type: string
        default: ./Dockerfile
      push:
        type: boolean

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        if: ${{ inputs.cache }}
        with:
          name: ${{ inputs.cache }}
          path: ${{ inputs.context }}
      - name: Restore the cache
        if: ${{ endsWith(inputs.cache, '.tar') }}
        run: |
          tar -xvf ${{ inputs.context }}/${{ inputs.cache }} -C ${{ inputs.context }}
          rm -rf ${{ inputs.context }}/${{ inputs.cache }}
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ inputs.name }}
      - uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.context }}/${{ inputs.file }}
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ github.ref_name }}-${{ inputs.name }}
          cache-to: type=gha,scope=${{ github.ref_name }}-${{ inputs.name }}
