name: Build docker image

on:
  workflow_call:
    inputs:
      registry:
        type: string
        default: mikojs
      name:
        required: true
        type: string
      cache_name:
        type: string
      cache_path:
        type: string
      context:
        type: string
        default: .
      file:
        type: string
        default: ./Dockerfile
      push:
        type: boolean
        default: false

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        if: ${{ inputs.cache_path != '' && inputs.cache_path != '' }}
        with:
          name: ${{ inputs.cache_name }}
          path: ${{ inputs.cache_path }}
      - run: tar -xvf ${{ inputs.cache_path }} && rm -rf ${{ inputs.cache_path }}
        if: ${{ inputs.cache_path != '' && inputs.cache_path != '' }} && endsWith(${{ inputs.cache_path}}, '.tar')
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v2
        id: meta
        with:
          images: ghcr.io/${{ inputs.registry }}/${{ inputs.name }}
      - uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
