name: Build docker image

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      cache-name:
        type: string
      cache-path:
        type: string
      pre-build:
        type: string
      context:
        type: string
        default: .
      file:
        type: string
        default: ./Dockerfile
      push:
        type: boolean
        default: false

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        if: ${{ inputs.cache-name != '' && inputs.cache-path != '' }}
        with:
          name: ${{ inputs.cache-name }}
          path: ${{ inputs.cache-path }}
      - run: ${{ inputs.pre-build }}
        if: ${{ inputs.pre-build != '' }}
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v2
        id: meta
        with:
          images: ghcr.io/${{ inputs.name }}
      - uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
