name: Build rust project

on:
  workflow_call:
    inputs:
      name:
        type: string
        default: rust
      manifest-path:
        type: string
        default: .

jobs:
  build-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ${{ inputs.manifest-path }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: >
            --release
            --target x86_64-unknown-linux-musl
            --target-dir ./_${{ inputs.name }}
            --manifest-path ${{ inputs.manifest-path }}
      - run: mkdir ./${{ inputs.name }}
      - run: >
          find ./_${{ inputs.name }}/x86_64-unknown-linux-musl/release
          -type f
          -maxdepth 1
          -executable
          -exec cp {} ./${{ inputs.name }} \;
      - run: tar -cvf ${{ inputs.name }}.tar ${{ inputs.name }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.name }}
          path: ./${{ inputs.name }}.tar
