name: Build docker image

on:
  workflow_call:
    inputs:
      cache:
        type: string
      name:
        required: true
        type: string
      context:
        type: string
        default: .
      file:
        type: string
      push:
        type: boolean

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        if: ${{ inputs.cache }}
        with:
          name: ${{ inputs.cache }}
          path: ${{ inputs.context }}
      - if: ${{ endsWith(inputs.cache, '.tar') }}
        run: tar -xcf ${{ inputs.context }}/${{ inputs.cache }}
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v2
        id: meta
        with:
          images: ghcr.io/${{ inputs.name }}
      - uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
