name: Build rust project

on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      manifest-path:
        type: string
        default: ./Cargo.toml

jobs:
  build-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo test --manifest-path ${{ inputs.manifest-path }}
      - run: >
          cargo build
          --release
          --target x86_64-unknown-linux-musl
          --target-dir ./target
          --manifest-path ${{ inputs.manifest-path }}
      - run: mkdir ./${{ inputs.name }}
      - run: >
          find ./target/x86_64-unknown-linux-musl/release
          -type f
          -maxdepth 1
          -executable
          -exec cp {} ./${{ inputs.name }} \;
      - run: tar -cvf ${{ inputs.name }}.tar ${{ inputs.name }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.name }}.tar
          path: ./${{ inputs.name }}.tar
