name: PR check

jobs:
  check-labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          any_of: Added,Changed,Deprecated,Removed,Fixed,Security
          repo_token: ${{ secrets.GITHUB_TOKEN }}
