name: PR check

on:
  workflow_call:

jobs:
  check-pr:
    name: Check PR
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        id: label_check
        with:
          any_of: Added,Changed,Deprecated,Removed,Fixed,Security
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          allow_failure: true
      - uses: babel/actions/create-comment@v2
        if: steps.label_check.outputs.label_check == 'failure'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue: ${{ github.event.pull_request.number }}
          comment: >
            Please add at least one of the labels in the PR:
            - Added
            - Changed
            - Deprecated
            - Removed
            - Fixed
            - Security
