name: Release

jobs:
  pre-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: generate changelog.md
      - uses: upgrade version on config
      - uses: add release git tag
      - uses: remove pre-release git tag
