name: tests

on: [push]

jobs:
  pre-build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "cache" >> cache
      - uses: actions/upload-artifact@v3
        with:
          name: cache
          path: ./cache
      - run: tar -cvf cache.tar cache
      - uses: actions/upload-artifact@v3
        with:
          name: cache-tar
          path: ./cache.tar

  build-docker:
    uses: ./.github/workflows/build-docker.yml
    needs: pre-build-docker
    strategy:
      matrix:
        include:
          - name: base
          - name: with-cache
            cache-name: cache
          - name: with-cache
            cache-name: cache-tar
            pre-build: tar -xvf ./.github/tests/cache.tar
    with:
      name: ${{ matrix.name }}
      cache-name: ${{ matrix.cache-name }}
      cache-path: ./.github/tests
      pre-build: ${{ matrix.pre-build }}
      context: ./.github/tests
      file: ./.github/tests/Dockerfile.${{ matrix.name }}

  final-check:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - uses: actions/checkout@v3
