name: tests

on: [push]

jobs:
  pre-build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "cache" >> cache
      - uses: actions/upload-artifact@v3
        with:
          name: cache
          path: ./cache
      - run: tar -cvf cache.tar cache
      - uses: actions/upload-artifact@v3
        with:
          name: cache.tar
          path: cache.tar

  build-docker:
    uses: ./.github/workflows/build-docker.yml
    needs: pre-build-docker
    strategy:
      matrix:
        include:
          - cache: cache
          - cache: cache.tar
    with:
      cache: ${{ matrix.cache }}
      name: mikojs/build-docker
      context: ./.github/tests/build-docker
      file: ./.github/tests/build-docker/Dockerfile

  build-rust:
    uses: ./.github/workflows/build-rust.yml
    with:
      manifest-path: ./.github/tests/build-rust/Cargo.toml

  post-build-rust:
    runs-on: ubuntu-latest
    needs: build-rust
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: rust
      - run: tar -xvf ./rust.tar
      - run: test "$(./rust/build-rust)" == "Hello, world!" || exit 1

  final-check:
    runs-on: ubuntu-latest
    needs:
      - build-docker
      - post-build-rust
    steps:
      - uses: actions/checkout@v3
