name: tests

on: [push]

jobs:
  pre-build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "cache" >> cache
      - uses: actions/upload-artifact@v3
        with:
          name: cache
          path: ./cache
      - run: tar -cvf cache cache.tar
      - uses: actions/upload-artifact@v3
        with:
          name: cache-tar
          path: ./cache.tar

  build-docker:
    uses: ./.github/workflows/build-docker.yml
    needs: pre-build-docker
    strategy:
      matrix:
        include:
          - name: base
          - name: with-cache
            cache_name: cache
            cache_path: ./.github/tests/cache
          - name: with-cache-tar
            cache_name: cache-tar
            cache_path: ./.github/tests/cache.tar
    with:
      name: ${{ matrix.name }}
      cache_name: ${{ matrix.cache_name }}
      cache_path: ${{ matrix.cache_path }}
      context: ./.github/tests
      file: ./.github/tests/Dockerfile.${{ matrix.name }}

  final-check:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - uses: actions/checkout@v3
