name: Test workflows

on: [push]

jobs:
  check-nix:
    uses: ./.github/workflows/check-nix.yml
    with:
      folder: ./.github/tests/nix
  check-rust:
    uses: ./.github/workflows/check-rust.yml
    with:
      folder: ./.github/tests/rust
