name: tests

on: [push]

jobs:
  pre-build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create the testing file
        run: echo "cache" >> cache
      - uses: actions/upload-artifact@v3
        with:
          name: cache
          path: ./cache
      - name: Compress the cache file
        run: tar -cvf cache.tar cache
      - uses: actions/upload-artifact@v3
        with:
          name: cache.tar
          path: ./cache.tar

  build-docker:
    uses: ./.github/workflows/build-docker.yml
    needs: pre-build-docker
    strategy:
      matrix:
        cache: [cache, cache.tar]
    with:
      cache: ${{ matrix.cache }}
      name: mikojs/${{ matrix.cache }}
      context: ./.github/tests/build-docker

  build-rust:
    uses: ./.github/workflows/build-rust.yml
    with:
      name: build-rust
      manifest-path: ./.github/tests/build-rust/Cargo.toml

  post-build-rust:
    runs-on: ubuntu-latest
    needs: build-rust
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build-rust.tar
      - name: Decompress the cache file
        run: tar -xvf ./build-rust.tar
      - name: Test the build file
        run: test "$(./build-rust/build-rust)" == "Hello, world!" || exit 1

  final-check:
    runs-on: ubuntu-latest
    needs:
      - build-docker
      - post-build-rust
    steps:
      - uses: actions/checkout@v3
